### ISSUE TITLE
If there's one user, the bounding box is very zoomed-in.

### ISSUE THREAD

**Issue by rawles** [timhutton/geofun#11]
When you are the only user on the map, and the 'show all users' button is pushed, an extreme close-up occurs. In this case, we could change the zoom behaviour to the 'show my location' button's.

**Comment by timhutton** [comment]
Try it now? I pushed a fix for this a few minutes ago.

**Comment by rawles** [comment]
Very fast! I can't; there's more than one user on the map!

**Comment by rawles** [comment]
Works really well, thanks.
