### ISSUE TITLE
New label suggestions for this tracker.

### ISSUE THREAD

**Issue by rawles** [timhutton/geofun#12]
Could we have 'client', 'server' and 'game idea' labels, so that I can easily view what problems people are having with the server, or see what ideas have been had?

**Comment by timhutton** [comment]
You can make whatever labels you want by going here: https://github.com/timhutton/geofun/labels

I don't mind having a 'server' label in addition to the Pn labels. But I like to keep a priority order on every issue, else we get a proliferation of categories and no clear path forwards.

**Comment by rawles** [comment]
We can do both.
