### ISSUE TITLE
Building blocks rather than pre-defined games

### ISSUE THREAD

**Issue by rawles** [timhutton/geofun#30]
At several points we’ve discussed how users might choose to form games out of their own game elements (e.g. ‘seeing where other people are’, ‘dropping boxes’, ‘colouring tiles’), and so it might be cool to consider a way that users could combine these themselves (with relevant privacy concerns deduced and reported). Who knows if the games we are devising are the most fun games that can be constructed from the game elements we’re writing?

**Comment by timhutton** [comment]
Merged with #21.
