### ISSUE TITLE
Location glitching

### ISSUE THREAD

**Issue by timhutton** [timhutton/geofun#5]
Some devices have glitchy location reporting, even in high accuracy mode. We should be able to have the client take more frequent location samples and keep a running average.

For extra points, use the accuracy figure as a weight or for some clever robust model.

**Comment by rawles** [comment]
I didn't notice this at the playtest at all! Your fixes must have really helped.

**Comment by timhutton** [comment]
With location 'watch' mode this issue seems to be resolved. Possibly at the expense of battery life.
